# Generated by Django 4.2.18 on 2025-01-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de conjunto de respuestas')),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='created_at',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=1, verbose_name='Pregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='response_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.responsegroup', verbose_name='Conjunto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='response_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.responsegroup', verbose_name='Conjunto de respuestas'),
            preserve_default=False,
        ),
    ]
