# Generated by Django 4.2.18 on 2025-01-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_campaign_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Campaigns', to='survey.survey', verbose_name='Encuesta'),
            preserve_default=False,
        ),
    ]
