# Generated by Django 4.2.18 on 2025-02-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_assignment_students_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completa'),
        ),
    ]
